### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Davidhuangwei** [Shiwei-Wu/myblog#1]
吴博士你好：
       我是一名无损检测研究生，你的博士论文令人印象非常深刻，请问你可以pull一些关于博士论文相关代码吗？

**Comment by Shiwei-Wu** [comment]
@Davidhuangwei  Hi，非常荣幸鄙人拙著能给人带来一些启发。由于我也已经毕业多年，且相关资料在毕业时已作为知识产权全部移交导师处理，而电脑里未有备份，非常遗憾！

您可以尝试联系我的导师（论文中应该留有他的邮箱）
另外，若有关于论文方面的问题，鄙人非常乐意与同行探讨。
